version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-movie-db
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - go-network
  db:
    image: postgres:15-alpine
    ports:
      - 5441:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie 
    container_name: db-movie-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - go-network
volumes:
  postgres_data:
networks:
  go-network:
    driver: bridge
