version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-movie-db
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movie 
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
